// Browser test for the customer login page. Run: node test/e2e/account.e2e.mjs
import serve from './serve.mjs';
import { launch } from './cdp.mjs';
import { mkdirSync } from 'node:fs';
const out = process.env.TEMP + '/btg-e2e'; mkdirSync(out, { recursive: true });
const server = await serve(4413);
const results = [];
const check = (name, ok, info = '') => { results.push(ok); console.log((ok ? 'ok   ' : 'FAIL ') + name + (info ? '  ' + info : '')); };
let b = await launch({ width: 1440, height: 900 });
await b.goto('http://localhost:4413/customer-log-in/');
check('new header', await b.evalJs(`document.documentElement.classList.contains('btg-header-on')`));
check('login form posts to wp-login.php with log/pwd', await b.evalJs(`(() => { const f = document.querySelector('.btg-acct-form'); return !!f && f.getAttribute('action') === '/wp-login.php' && f.method === 'post' && !!f.querySelector('[name=log]') && !!f.querySelector('[name=pwd][type=password]'); })()`));
check('return address is this page', await b.evalJs(`document.querySelector('[name=redirect_to]').value === '/customer-log-in/'`));
check('two cards side by side on desktop', await b.evalJs(`(() => { const c = document.querySelectorAll('.btg-acct-card'); return c.length === 2 && Math.abs(c[0].getBoundingClientRect().top - c[1].getBoundingClientRect().top) < 8; })()`));
await b.evalJs(`document.querySelector('#btg-log').focus()`);
check('focused field has the green ring', await b.evalJs(`getComputedStyle(document.querySelector('#btg-log')).boxShadow.includes('56, 121, 47')`));
check('no horizontal scroll', !(await b.evalJs(`document.documentElement.scrollWidth > innerWidth`)));
await b.evalJs(`document.querySelector('.btg-account').scrollIntoView()`); await b.sleep(500);
await b.shot(out + '/acct-login.png');
await b.evalJs(`document.querySelector('.btg-account').innerHTML = window.BTGAccount.hubHtml()`); await b.sleep(300);
check('signed-in hub lists 4 links', await b.evalJs(`document.querySelectorAll('.btg-acct-tile').length === 4`));
await b.shot(out + '/acct-hub.png');
await b.close();
b = await launch({ width: 390, height: 800 });
await b.goto('http://localhost:4413/customer-log-in/');
check('phone: one column, no horizontal scroll', await b.evalJs(`(() => { const c = document.querySelectorAll('.btg-acct-card'); return c[1].getBoundingClientRect().top > c[0].getBoundingClientRect().bottom - 2 && document.documentElement.scrollWidth <= innerWidth; })()`));
await b.evalJs(`document.querySelector('.btg-account').scrollIntoView()`); await b.sleep(500);
await b.shot(out + '/acct-phone.png');
await b.close(); server.close();
const bad = results.filter((x) => !x).length; console.log(`${results.length - bad}/${results.length} passed`); process.exit(bad ? 1 : 0);
