// Browser test for v1.6.2. Run: node test/e2e/grok-fixes.e2e.mjs
import serve from './serve.mjs';
import { launch } from './cdp.mjs';
import { mkdirSync } from 'node:fs';
const out = process.env.TEMP + '/btg-e2e'; mkdirSync(out, { recursive: true });
const server = await serve(4440);
const results = [];
const check = (name, ok, info = '') => { results.push(ok); console.log((ok ? 'ok   ' : 'FAIL ') + name + (info ? '  ' + info : '')); };

const count = `[...document.querySelectorAll('li')].filter((l) => l.querySelector(':scope > a') && l.querySelector(':scope > a').textContent.trim() === 'Customer Log In').length`;
let b = await launch({ width: 1440, height: 900 });
await b.goto('http://localhost:4440/');
await b.sleep(1800);
check('desktop: no Customer Log In menu item (v1.6.7)', await b.evalJs(count) === 0, 'copies: ' + await b.evalJs(count));
check('NJ line links to /northern-new-jersey/', await b.evalJs(`(() => { const a = document.querySelector('.btg-hero-alt a'); return !!a && new URL(a.href).pathname === '/northern-new-jersey/' && a.parentNode.previousElementSibling.classList.contains('btg-hero-trust'); })()`));
check('footer: no Instagram widget, no Tweets by', await b.evalJs(`(() => { const f = document.querySelector('.fusion-footer'); return !f.querySelector('#text-18') && !f.querySelector('#text-17') && f.innerText.toLowerCase().indexOf('instagram') < 0 && f.innerText.indexOf('Tweets by') < 0; })()`));
check('footer: veteran badge and the Virginia and NJ area links stay', await b.evalJs(`!!document.querySelector('.fusion-footer #text-16 .btg-vet') && !!document.querySelector('.fusion-footer a[href$="/best-computer-repair-chesterfield-va/"]') && !!document.querySelector('.fusion-footer a[href$="/northern-new-jersey/"]')`));
check('no horizontal scroll', !(await b.evalJs(`document.documentElement.scrollWidth > innerWidth`)));
await b.evalJs(`scrollTo(0, 0)`); await b.sleep(300);
await b.shot(out + '/grok-hero.png');
await b.evalJs(`document.querySelector('.fusion-footer').scrollIntoView()`); await b.sleep(500);
await b.shot(out + '/grok-footer.png');
await b.close();
b = await launch({ width: 390, height: 844, mobile: true });
await b.goto('http://localhost:4440/');
await b.sleep(2500);
check('phone: mobile menu has no Customer Log In either', await b.evalJs(count) === 0 && await b.evalJs(`document.querySelectorAll('.fusion-mobile-nav-item, .fusion-mobile-menu li').length`) > 3, 'copies: ' + await b.evalJs(count));
check('phone: no horizontal scroll', !(await b.evalJs(`document.documentElement.scrollWidth > innerWidth`)));
await b.close();
b = await launch({ width: 1440, height: 900 });
await b.goto('http://localhost:4440/contact-2/');
await b.sleep(1500);
check('contact: one privacy note right after .wpcf7 with mailto', await b.evalJs(`(() => { const n = document.querySelectorAll('.btg-privacy-note'); const w = document.querySelector('.wpcf7'); return n.length === 1 && w.nextElementSibling === n[0] && !!n[0].querySelector('a[href="mailto:info@bobthetechguy.com"]'); })()`));
await b.close(); server.close();
const bad = results.filter((x) => !x).length; console.log(`${results.length - bad}/${results.length} passed`); process.exit(bad ? 1 : 0);
