// Browser test for v1.6.0 on the Northern New Jersey stand-in page. Run: node test/e2e/reviews-nj.e2e.mjs
import serve from './serve.mjs';
import { launch } from './cdp.mjs';
import { mkdirSync } from 'node:fs';
const out = process.env.TEMP + '/btg-e2e'; mkdirSync(out, { recursive: true });
const server = await serve(4430);
const results = [];
const check = (name, ok, info = '') => { results.push(ok); console.log((ok ? 'ok   ' : 'FAIL ') + name + (info ? '  ' + info : '')); };
let b = await launch({ width: 1440, height: 900 });
await b.send('Debugger.enable');
const parsed = [];
b.on('Debugger.scriptParsed', (p) => parsed.push(p.url));
await b.goto('http://localhost:4430/northern-new-jersey/');
await b.sleep(1500);
check('crypto widget script never runs', parsed.some((u) => /btg.js/.test(u)) && !parsed.some((u) => /coinmarketcap/.test(u)), parsed.filter((u) => /coinmarketcap|btg/.test(u)).join(' '));
check('crypto widget element removed', await b.evalJs(`!document.querySelector('.coinmarketcap-currency-widget')`));
check('reviews band in the slot with 12 cards', await b.evalJs(`!!document.querySelector('.btg-rv-slot .btg-rv') && document.querySelectorAll('.btg-rv-card').length === 12`));
check('summary shows on-site numbers, no Google claim', await b.evalJs(`(() => { const t = document.querySelector('.btg-rv-sum').innerText; return /5\\.0/.test(t) && /7 star ratings/.test(t) && !/Google/.test(t); })()`));
check('Read more expands a clamped review', await b.evalJs(`(() => { const btn = document.querySelector('.btg-rv-more'); const p = document.getElementById(btn.getAttribute('aria-controls')); const h1 = p.getBoundingClientRect().height; btn.click(); return btn.getAttribute('aria-expanded') === 'true' && p.getBoundingClientRect().height > h1; })()`));
check('Next button scrolls the cards', await b.evalJs(`new Promise((ok) => { const t = document.querySelector('.btg-rv-track'); const x = t.scrollLeft; document.querySelector('.btg-rv-next').click(); setTimeout(() => ok(t.scrollLeft > x), 900); })`));
check('footer NJ links point to the new page, one entry left', await b.evalJs(`(() => { const a = [...document.querySelectorAll('.fusion-footer a')].filter((x) => /new-jersey|-nj\\//.test(x.href)); return a.length >= 1 && a.every((x) => x.pathname === '/northern-new-jersey/') && a.filter((x) => x.closest('li')).length === 1; })()`), await b.evalJs(`JSON.stringify([...document.querySelectorAll('.fusion-footer a')].filter((x) => /new-jersey|-nj/.test(x.href)).map((x) => x.pathname + ' ' + x.textContent.trim()))`));
check('15 service links and towns listed', await b.evalJs(`document.querySelectorAll('.btg-sr-item').length === 15 && document.querySelectorAll('.btg-nj-towns li').length === 23`));
check('no horizontal scroll', !(await b.evalJs(`document.documentElement.scrollWidth > innerWidth`)));
await b.evalJs(`document.querySelector('.btg-rv').scrollIntoView({ block: 'center' })`); await b.sleep(700);
await b.shot(out + '/nj-reviews.png');
await b.evalJs(`scrollTo(0, 420)`); await b.sleep(500);
await b.shot(out + '/nj-top.png');
await b.close();
b = await launch({ width: 390, height: 844, mobile: true });
await b.goto('http://localhost:4430/northern-new-jersey/');
await b.sleep(1000);
check('phone: no horizontal scroll', !(await b.evalJs(`document.documentElement.scrollWidth > innerWidth`)));
check('phone: a card fits the screen', await b.evalJs(`document.querySelector('.btg-rv-card').getBoundingClientRect().width <= innerWidth - 20`));
await b.evalJs(`document.querySelector('.btg-rv').scrollIntoView()`); await b.sleep(700);
await b.shot(out + '/nj-reviews-phone.png');
await b.close(); server.close();
const bad = results.filter((x) => !x).length; console.log(`${results.length - bad}/${results.length} passed`); process.exit(bad ? 1 : 0);
